# Generated by Django 4.2.2 on 2023-06-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=40, unique=True, verbose_name='Your email')),
                ('password', models.CharField(max_length=255, verbose_name='Your password')),
                ('information', models.TextField(max_length=1000, verbose_name='Information about yourself')),
                ('count_article', models.PositiveIntegerField(verbose_name='Count articles')),
                ('avatar', models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Your avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
