# Generated by Django 4.2.2 on 2023-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ireal', unique=True, verbose_name='User login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='User avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True, verbose_name='User email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='information',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Information about user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='User password'),
        ),
    ]
