# Generated by Django 4.2.2 on 2023-06-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_name_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
