# Generated by Django 4.2.2 on 2023-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='User login'),
        ),
    ]
