# Generated by Django 4.2.2 on 2023-06-26 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Article name')),
                ('text', models.TextField(max_length=100000, verbose_name='Article text')),
                ('average_rate', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Article average rate')),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 18, 4, 15, 931665), verbose_name='Article publication date')),
                ('count_like', models.PositiveIntegerField(default=0, verbose_name='Article count like')),
                ('count_dislike', models.PositiveIntegerField(default=0, verbose_name='Article count dislike')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Comment text')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 18, 4, 15, 931665), verbose_name='Comment date')),
                ('count_like', models.PositiveIntegerField(default=0)),
                ('count_dislike', models.PositiveIntegerField(default=0)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
