# Generated by Django 4.2.2 on 2023-06-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Article name')),
                ('text', models.TextField(max_length=100000, verbose_name='Article text')),
                ('average_rate', models.FloatField(verbose_name='Article average rate')),
                ('publication_date', models.DateTimeField(verbose_name='Article publication date')),
                ('count_like', models.PositiveIntegerField(default=0, verbose_name='Article count like')),
                ('count_dislike', models.PositiveIntegerField(default=0, verbose_name='Article count dislike')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Comment text')),
                ('date', models.DateTimeField()),
                ('count_like', models.PositiveIntegerField()),
                ('count_dislike', models.PositiveIntegerField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='genre_id',
            field=models.ManyToManyField(to='articles.genre'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
