# Generated by Django 4.2.2 on 2023-06-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Article average rate'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
    ]
