# Generated by Django 4.2.2 on 2023-06-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_average_rate_alter_article_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
    ]
