# Generated by Django 4.2.2 on 2023-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_comment_id_remove_article_tag_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='tag_id',
            field=models.ManyToManyField(to='articles.tag'),
        ),
    ]
