# Generated by Django 4.2.2 on 2023-06-25 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_comment_count_dislike_alter_comment_count_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Article average rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 16, 18, 47, 583562), verbose_name='Comment date'),
        ),
    ]
